//
// Created by admin on 20.12.2023.
//

#ifndef DONKEYKONG_DEFINES_H
#define DONKEYKONG_DEFINES_H
#include "Magic.h"

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define MAREK_X 18
#define MAREK_Y 420
#define MAREK_WIDTH 32
#define MAREK_SPEED 70
#define LADDER_SPEED 50
#define PLATFORMS 6
#define PLATFORM_HEIGHT 15
#define PLATFORM1_X 0
#define PLATFORM1_Y 465
#define PLATFORM1_WIDTH SCREEN_WIDTH
#define PLATFORM2_X 45
#define PLATFORM2_Y 389
#define PLATFORM2_WIDTH (SCREEN_WIDTH-100)
#define PLATFORM3_X 52
#define PLATFORM3_Y 315
#define PLATFORM3_WIDTH (SCREEN_WIDTH-127)
#define PLATFORM4_X 85
#define PLATFORM4_Y 241
#define PLATFORM4_WIDTH (SCREEN_WIDTH-180)
#define PLATFORM5_X 106
#define PLATFORM5_Y 168
#define PLATFORM5_WIDTH (SCREEN_WIDTH-224)
#define PLATFORM6_X 165
#define PLATFORM6_Y 91
#define PLATFORM6_WIDTH (SCREEN_WIDTH-343)
#define LADDERS 9
#define LADDERS_WIDTH 20
#define LADDERS_HEIGHT 76
#define FPS_REFRESH_TIME 0.5
#define FPS_ADJUSTED_TIME (1 / FPS_REFRESH_TIME)

//colors

#endif //DONKEYKONG_DEFINES_H
